name: jar_form
description: Reactive form management for Flutter with JAR validation schema support.
version: 1.0.0
repository: https://github.com/julianramireze/jar_form
homepage: https://github.com/julianramireze/jar_form

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  jar: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.21.6
  build_runner: ^2.3.0

flutter:
  # No assets needed